name: 'Bug Report'
description: 'Report an issue with a project. ONE ISSUE PER REPORT'
title: "[Bug]: "
labels: ["bug"]
assignees:
  - itsjusttriz
body:
  - type: 'markdown'
    attributes:
      value: '## If you are having more than one issue, please open separate bug
        reports'
  - type: 'dropdown'
    id: 'ijt-projects-dropdown'
    attributes:
      label: 'Project'
      description: 'What project are you having an issue with?'
      options:
        - 'www.itsjusttriz.com'
        - 'Other...'
    validations:
      required: true
  - type: 'textarea'
    id: 'bugdesc'
    attributes:
      label: 'Describe the bug'
      description: 'A clear and concise description of what the bug is

        '
    validations:
      required: true
  - type: 'textarea'
    id: 'reproduce'
    attributes:
      label: 'Steps to reproduce'
      description: 'Tell us how we can reproduce the issue'
      placeholder: '1. Go to ...

        2. Click on ...

        3. Scroll down to ...

        4. See error

        '
    validations:
      required: true
  - type: 'textarea'
    id: 'expectedBehaviour'
    attributes:
      label: 'Expected behaviour'
      description: 'A clear and concise description of what you expected to happen.

        '
    validations:
      required: true
  - type: 'textarea'
    id: 'screenshots'
    attributes:
      label: 'Screenshots'
      description: 'If applicable, add screenshots to help explain your problem.'
  - type: 'textarea'
    id: 'additional'
    attributes:
      label: 'Additional information'
      description: 'Add any other context about the problem here'
